update policy agent chart to version 2.0.0
weaveworks/weave-gitops-profile-examples pull request #86
Opened 2022-11-09 09:07 UTC by ahsayde

fixes https://github.com/weaveworks/weave-gitops-profile-examples/issues/83

2022-11-09 09:47 UTC, serboctor approved these changes

2022-11-09 09:48 UTC, serboctor approved these changes

2022-11-09 09:49 UTC, serboctor requested changes

2022-11-09 09:49 UTC, serboctor commented on charts/weave-policy-agent/Chart.yaml
>  appVersion: "1.2.1"
shouldnt this be 2.0.0?

2022-11-09 10:23 UTC, waleedhammam approved these changes

2022-11-09 10:34 UTC, serboctor approved these changes

2022-11-15 09:28 UTC, waleedhammam approved these changes

2022-11-16 10:43 UTC, merged